Add github actions and ingress configuration
navikt/soknad-html-generator pull request #41
Opened 2021-05-26 07:55 UTC by MengZhuNAV

The application needs ingress configuration to enable access from GCP

2021-05-31 08:31 UTC, hensol requested changes
Bra, bør gå over til å bruke  ghcr. Og hvis vi samtidig kunne gått over til team namespace istedenfor default hadde det vært supert

2021-05-31 08:31 UTC, hensol commented on .github/workflows/build_n_deploy_dev.yaml
> +  IMAGE: docker.pkg.github.com/${{ github.repository }}/soknad-kontantstotte-html:${{ github.sha }}
Bør bruke ghcr siden det gamle docker pkg repoet skal fases ut. Her er ett eksempel på hvordan det skal brukes
https://github.com/navikt/familie-ks-mottak/commit/41648a036c685ed7483d0a946eec0c4f8d671ae7

2021-05-31 09:16 UTC, MengZhuNAV commented on .github/workflows/build_n_deploy_dev.yaml
> +  IMAGE: docker.pkg.github.com/${{ github.repository }}/soknad-kontantstotte-html:${{ github.sha }}
Ok, it seems working, but please have a look to see if it is correct

2021-05-31 12:21 UTC, hensol requested changes
Topp, men kan vi ikke flytte denne direkte til gcp når vi først er igang?

2021-05-31 12:21 UTC, hensol commented on .github/workflows/build_n_deploy_dev.yaml
> +  IMAGE: ghcr.io/navikt/soknad-kontantstotte-html:${{ github.sha }}
👍

2021-05-31 12:21 UTC, hensol commented on .github/workflows/build_n_deploy_dev.yaml
> +          CLUSTER: dev-sbs
kan vi ikke flytte denne direkte til gcp og team namespace?

2021-05-31 12:21 UTC, hensol commented on .github/workflows/build_n_deploy_prod.yaml
> +          CLUSTER: prod-sbs
kan ikke denne flyttes direkte til gcp?

2021-05-31 12:21 UTC, hensol commented on app-prod.yaml
> +    - "https://soknad-html-generator.nais.oera.no/"
hvis vi flytter direkte til gcp er det egne ingresser 
https://doc.nais.io/clusters/gcp/#prod-gcp-ingresses

2021-06-01 18:43 UTC, hensol approved these changes

2021-06-02 07:53 UTC, merged